### PR TITLE
Michaels branch

### PR DESCRIPTION
**Pull request by DriftKing1998**
I added the basics of NC-MCM. The behavioral_state_diagram has a lot of booleans. I did not test all combinations but the most important ones. 
The test for the clustering of neuronal time series takes some time since it tests for Markov properties. The html file in the tests directory is created each time we run the tests (overwritten). I could not keep that from happening, but I think it's no problem. If it is we can delete it each time (within the test methods?).

- changed test-file name

- added behavioral_state_diagram with tests

- added clustering of neuronal time series with tests

- said clustering will also test 2 Markov properties (memorylessness and stationarity)

### CODE REVIEW

**Comment by DriftKing1998** [comment]
Hi Akshey,
what does this mean exactly?
are the arrays in the test functions too big? Or was there an error with the import?
I am not sure?

**Comment by DriftKing1998** [comment]
After looking into it, it seems there is an import error with pyvis for the interactive graph. On my branch, the import worked fine. The only problem I had with pyvis was that I had to set:

pip install markupsafe==2.0.1

**Comment by akshey-kumar** [comment]
Hi Michael,
Thanks for adding the tests. It looks like there was an error involving some imports.

Since you say it works for you with pip installing some package, could you add this to the setup? Hopefully, then, it should run fine and pass the tests.

If it works in your environment, it might also be a good idea to do a pip freeze and add all the packages from there to the setup. I'm not sure what is the best way to do this though.

**Comment by DriftKing1998** [comment]
Hi Akshey,
I think I identified the issue. Tensorflow version 2.13.0rc2 depends on a version of typing_extensions between <4.6.0 and >=3.6.6, while pyvis depends on a version >=4.6.0. 

Can we change the requirement for the Tensorflow version? 
I tried using a newer version, but then the tests for "BundleNet" failed. What is the reason for using version 2.13.0rc2? Maybe I can find a solution. Otherwise, I would need to exclude pyvis and with it the HTML graphs for now.

**Comment by DriftKing1998** [comment]
Hi Akshey, 
I got it to work i changed three things in the setup.py file.

numpy==1.25.2
tensorflow==2.14.0
typing_extensions==4.6.0

I used this versions since all tests passed in my env locally with these.
pyvis needs at least typing_extensions version 4.6.0, however tensorflow version 2.13.0rc2 which we had before, needs <4.6.0. Therefore I used i newer version of tensorflow, which in turn forced me to use an older numpy version, otherwise i got some python type error. 

If you want the newer versions, I also tested it locally with:

numpy==1.26.4
tensorflow==2.15.0
typing_extensions==4.6.0

And it also seemed to pass all tests, so we could also use these versions in the setup file if preferred. Sometimes I got an error in the "test_bundlenet_training_best_of_5_init" for the discrete models. However, this error was inconsistent and seemed to be caused by extreme input values and not because of the versions.

Best regards,
Michael

**Comment by akshey-kumar** [comment]
Hi Michael,

Thank you for resolving the conflicting dependencies! I am glad that it works now when put together. Good job!

In general, it is always better to use newer versions. Could you tell me a bit more about the error you got from 'test_bundlenet_training_best_of_5_init'. Maybe there's a way I can change that test so it does not result in these extreme values?

Best,
Akshey

**Pull request merged**
